# Generated by Django 3.0.7 on 2020-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
