# Generated by Django 3.0.7 on 2020-09-29 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
